// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApgv-j-TTf33hT78NNg4Nh8f_mvTn_Ww4',
    appId: '1:283747170634:web:3b9fec764bcc4d65a2a9b3',
    messagingSenderId: '283747170634',
    projectId: 'anirecord-955d7',
    authDomain: 'anirecord-955d7.firebaseapp.com',
    storageBucket: 'anirecord-955d7.appspot.com',
    measurementId: 'G-G3E5K9JDXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaHpytF8x-NPuSfTA56AMk9W8t3i1Xfgc',
    appId: '1:283747170634:android:753308465ab6c43da2a9b3',
    messagingSenderId: '283747170634',
    projectId: 'anirecord-955d7',
    storageBucket: 'anirecord-955d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJFDeeduAzh7ButlPKbGiwvFmN1MiAk8',
    appId: '1:283747170634:ios:de847dc8625e0ddba2a9b3',
    messagingSenderId: '283747170634',
    projectId: 'anirecord-955d7',
    storageBucket: 'anirecord-955d7.appspot.com',
    androidClientId: '283747170634-avuh5f7ri09jqvt113io3e2rp2pv9t5e.apps.googleusercontent.com',
    iosClientId: '283747170634-chc0k44m5r1nlse7aeplqs3jd9kqpqul.apps.googleusercontent.com',
    iosBundleId: 'com.star.anirecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJFDeeduAzh7ButlPKbGiwvFmN1MiAk8',
    appId: '1:283747170634:ios:1ac81f9165ae78f0a2a9b3',
    messagingSenderId: '283747170634',
    projectId: 'anirecord-955d7',
    storageBucket: 'anirecord-955d7.appspot.com',
    androidClientId: '283747170634-avuh5f7ri09jqvt113io3e2rp2pv9t5e.apps.googleusercontent.com',
    iosClientId: '283747170634-ck3aghukk2i8g5474vj6af7f9bvr6suv.apps.googleusercontent.com',
    iosBundleId: 'com.star.anirecord.RunnerTests',
  );
}
